// products
export const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST"
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS"
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL"

// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// cart page
export const CART_LIST_REQUEST = "CART_LIST_REQUEST"
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS"
export const CART_LIST_FAIL = "CART_LIST_FAIL"
export const CART_LIST_RESET = "CART_LIST_RESET"

// add to cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET"

// update cart item
export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAIL = "UPDATE_CART_ITEM_FAIL"
export const UPDATE_CART_ITEM_RESET = "UPDATE_CART_ITEM_RESET"

// delete cart item
export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST"
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS"
export const DELETE_CART_ITEM_FAIL = "DELETE_CART_ITEM_FAIL"
export const DELETE_CART_ITEM_RESET = "DELETE_CART_ITEM_RESET"
